{
 "title": "OVMS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interface", "label": "interface", "query": "gRPC, REST" }
  ]
 },
 "panels": [
  {
   "title": "OVMS Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(ovms_request_time_us_count{interface=\"REST\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OVMS Inference Execution Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(ovms_inference_time_us_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OVMS Requests Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(ovms_requests_success{method=\"ModelInfer\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OVMS Requests Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(ovms_requests_fail[5m])", "legendFormat": "__auto" }
   ]
  }
 ]
}